ProfitAndLoss:
  Revenue:
    keywords: ["Revenue", "Turnover", "Sales", "Total revenue", "Net revenue"]
  Gross Profit/Loss:
    keywords: ["Gross Profit", "Gross Loss", "Gross Profit/Loss", "Gross profit / (loss)"]
  Profit/Loss Before Tax:
    keywords: ["Profit Before Tax", "Loss Before Tax", "PBT", "Operating result before tax", "Profit/(loss) before tax"]
  Net Profit/Loss:
    keywords: ["Net Profit", "Net Loss", "Profit for the Year", "Net Profit/Loss", "Annual result", "Annual on result", "Net profit / (loss)", "Net profit (loss)", "Profit / (loss) for the year", "Total comprehensive income", "Total comprehensive profit", "Total comprehensive loss"]
  Operating Profit/Loss:
    keywords: ["Operating Profit", "Operating Loss", "Operating Profit/Loss", "Result of operations", "Operating profit / (loss)"]
  Cost of Sales:
    sign: negative
    keywords: ["Cost of Sales", "Cost of Goods Sold", "Total Operating expenses", "Total Operating Staff Depreciation", "Cost of revenue"]

Assets:
  Cash and Cash Equivalents:
    keywords: ["Cash and Cash Equivalents", "Cash & Cash Equivalents", "Bank deposits, cash in hand", "Bank deposits", "Cash and bank balances"]
  Current Assets:
    keywords: ["Current Assets", "Total Current Assets", "Total current asset"]
  Non-Current Assets:
    keywords: ["Non-Current Assets", "Noncurrent Assets", "Total fixed assets", "Total Non-Current Assets", "Total non-current asset"]
  Plant and Equipment:
    keywords:
      - "Plant and Equipment"
      - "Property Plant and Equipment"
      - "Property, plant and equipment"
      - "PP&E"
      - "plant and machinery"
      - "plant equipment"
      - "Tangible fixed assets"
      - "Fixtures and fittings"
      - "Machinery and equipment"
      - "Plant, machinery and equipment"
  Trade Receivables:
    keywords:
      - "Trade Receivables"
      - "trade and other receivables"
      - "accounts receivable"
      - "trade debtors"
      - "receivables from customers"
      - "net receivables"
      - "trade receivable"
  Total Assets:
    keywords: ["Total Assets", "Total assets"]

Liabilities:
  Current Liabilities:
    keywords:
      - "Current Liabilities"
      - "short-term liabilities"
      - "shorL-term"
      - "Total Current Liabilities"
      - "Total current liability"
      - "Total current liabilities"
      - "Trade payables and accrued costs"
      - "Accounts payable and accrued liabilities"
  Non-Current Liabilities:
    keywords:
      - "Non-Current Liabilities"
      - "Noncurrent Liabilities"
      - "Total Non-Current Liabilities"
      - "Total non-current liability"
      - "Long-term liabilities"
      - "Long term liabilities"
      - "Lease liabilities"
      - "Long-term borrowings"
      - "Borrowings"
      - "Finance lease liabilities"
  Total Liabilities:
    keywords: ["Total Liabilities", "Total ilities"]

Equity:
  Paid Up Capital:
    keywords: ["Paid Up Capital", "Share Capital", "Issued capital", "Ordinary shares"]
  Retained Earnings:
    keywords: ["Retained Earnings", "Accumulated Profits", "Accumulated Losses", "Retained profits", "Retained profit / (loss)", "Other equity"]
  Total Equity:
    keywords: ["Total Equity", "Total Shareholders' Equity", "Total equity", "Equity attributable to owners", "Equity attributable to owner"]

Auditor:
  Auditor's Opinion:
    keywords:
      - "Opinion"
      - "In our opinion"
      - "independent auditor"
      - "auditors report"
      - "independent auditors report"
      - "report of the independent"
      - "basis for opinion"
      - "qualified opinion"
      - "unqualified opinion"
      - "adverse opinion"
      - "disclaimer of opinion"
      - "emphasis of matter"
